workspace(name = "my_raylib_project")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "raylib_macos",
    urls = ["https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_macos.tar.gz"],
    strip_prefix = "raylib-5.0_macos",
    build_file = "//third_party:raylib.BUILD",
)

http_archive(
    name = "raylib_windows",
    urls = ["https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_msvc16.zip"],
    strip_prefix = "raylib-5.0_win64_msvc16",
    build_file = "//third_party:raylib.BUILD",
)

http_archive(
    name = "raylib_linux",
    urls = ["https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_linux_amd64.tar.gz"],
    strip_prefix = "raylib-5.0_linux_amd64",
    build_file = "//third_party:raylib.BUILD",
)
